# Generated by Django 5.1.4 on 2024-12-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_comment_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('assembling', 'Собираем'), ('in_transit', 'Заказ в пути'), ('completed', 'Выполнен')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
